### ISSUE TITLE
Search by ID in Payroll History and Calculate Payroll

### ISSUE THREAD

**Issue by JohnBadels** [Brasprin/Entom-System#9]
![image](https://github.com/user-attachments/assets/a9790bd6-d6e3-47a1-86de-ff49b57d1314)
![image](https://github.com/user-attachments/assets/8f408f6c-b041-435f-9cce-8f2b1de527ca)

Currently, when searching by ID, it only displays the user with the exact ID number. In the second picture, you can see that there is only one result when inputting "1," despite having several ID numbers with the number 1 (as seen in the first picture).

Suggestion: Instead of searching for the exact ID number, search for any ID number that has the number inputted on the "Search by ID" field.

**Comment by diegoh123** [comment]
search by id now includes any employees that has the specified number in the search field

**Comment by diegoh123** [comment]
search by id now includes any employees that has the specified number in the search field
